# Module4



**Data Structures**

Collections of data values or objects that contain different data types

#### What you'll learn
- Lists
- Tuples
- Dictionaries
- Sets
- Arrays
----
- Numpy
- pandas



## List and tuples

### Introduction to Lists


#### Data Structures

##### List
A data structure that helps store and manipulate an ordered collections of items.

| List | Strings |
|:---: | :---: |
| Data structure| Data type |
| Allow duplicate elements | Allow deplicate elements |
| Allow indexing and slicing | Allow indexing and slicing |
| Sequences of elements | Sequences of characters |

**Sequence**

A positionally ordered collection of items.

**Mutability**

The ability to change the internal state of a data structure.

**Immutability**

A data structure or element's can never be altered or updated.

In [23]:
x=['Now','we','are','cooking','with',7,'ingredients']
print(x[3])

cooking


In [24]:
x[1:3]

['we', 'are']

In [25]:
x[:2]

['Now', 'we']

In [26]:
type(x)

list

In [27]:
'we' in x

True

### Modify the contents of a list

```
append()
```
Method that adds an element to the end of a list

In [28]:
fruits=['pineapple','banana','apple','melon']
print(fruits)

['pineapple', 'banana', 'apple', 'melon']


In [29]:
fruits.append('kiwi')
print(fruits)

['pineapple', 'banana', 'apple', 'melon', 'kiwi']


```
insert()
```
Function that takes an index as the first paramater and an element as the second paramater., then inserts the element into a list at the given index.


In [31]:
fruits.insert(1,'orange')
print(fruits)

['pineapple', 'orange', 'orange', 'banana', 'apple', 'melon', 'kiwi']


In [32]:
fruits.insert(0,'mango')
print(fruits)

['mango', 'pineapple', 'orange', 'orange', 'banana', 'apple', 'melon', 'kiwi']


```
remove()
```
A method that removes an element from a list

In [33]:
fruits.remove('banana')
print(fruits)

['mango', 'pineapple', 'orange', 'orange', 'apple', 'melon', 'kiwi']


```
pop()
```
A method that extracters an elements from a list by removing it at a given index

In [34]:
fruits.pop(2)
print(fruits)

['mango', 'pineapple', 'orange', 'apple', 'melon', 'kiwi']


In [35]:
fruits[3]='mango'
print(fruits)

['mango', 'pineapple', 'orange', 'mango', 'melon', 'kiwi']


In [36]:
power='1.21'
power=power+'gigawatts'
print(power)

1.21gigawatts


In [37]:
power=['1.21','gigawatts']
power[0]=2.21
print(power)

[2.21, 'gigawatts']


In [39]:
empty_list=list()
print(empty_list)

[]


In [3]:
phrase=['Astra','inclinant','sed','non','obligant']
print(phrase[1:4])

['inclinant', 'sed', 'non']


In [4]:
my_list=['Macuduff','Malcolm','Macbeth','Banquo',]
my_list[1:3]=[1,2,3,4,5]
print(my_list)

['Macuduff', 1, 2, 3, 4, 5, 'Banquo']


In [6]:
num_list=[1,2,3]
char_list=['a','b','c']
num_list+char_list

[1, 2, 3, 'a', 'b', 'c']

In [7]:
list_a=['a','b','c']
list_a *2

['a', 'b', 'c', 'a', 'b', 'c']

In [8]:
num_list=[2,4,6]
print(5 in num_list)
print(5 not in num_list)

False
True


In [9]:
#remove the fiorst occurrence of an item:

my_list=['a','b','c','d']
my_list.remove('a')
print(my_list)

['b', 'c', 'd']


In [10]:
# .pop() removes and returns the last item in the list
 
my_list=['a','b','c','d']
print(my_list.pop())
print(my_list)

d
['a', 'b', 'c']


In [11]:
# remove all items

my_list=['a','b','c']
my_list.clear()
print(my_list)

[]


In [12]:
my_list=['a','b','c','d']
my_list.index('b')

1

In [14]:
my_list=['a','b','c','d']
my_list.count('a')

1

In [24]:
# sort(),sorts the list ascending by default, you can also make a function to decide the sorting criteria

char_list=['a','b','c','d']
num_list=[2,5,6,7,8,2,1,0]
char_list.sort()
num_list.sort(reverse=True)
print(num_list)
print(char_list)


[8, 7, 6, 5, 2, 2, 1, 0]
['a', 'b', 'c', 'd']


https://docs.python.org/3/tutorial/introduction.html#lists

https://docs.python.org/3/tutorial/datastructures.html

### Introduction to tuples

#### Tuple
An immutable sequence that can contain elements of any data type.


Tuples are expressed with parentheses or the `touple()` function

In [25]:
fullname=('Masha','Z','Hopper')

In [29]:
fullname=fullname+('Jr',)
print(fullname)


('Masha', 'Z', 'Hopper', 'Jr', 'Jr')


```
tuple()
```
Function that transforms input into tuples


In [30]:
fullname=['Masha','Z','Hopper']
fullname=tuple(fullname)
print(fullname)

('Masha', 'Z', 'Hopper')


In [31]:
def to_dollars_cents(price):
    '''
    Split price(float) into dollars and cents
    '''
    dollars=int(price//1)
    cents=round(price%1*100)

    return dollars,cents

In [32]:
to_dollars_cents(5.7890)

(5, 79)

In [40]:
dollars,cents=to_dollars_cents(6.879)
print(dollars+1)
print(cents+1)

7
89


In [41]:
type(cents)

int

In [42]:
team=[('Marta',28,'center'),
     ('Ana',22,'point guard'),
     ('Gabi',22,'shooting guard'),
     ('Luz',21,'power forward'),
     ('Lorema',18,'small forward')
     ]

In [43]:
for name, age, position in team:
    print(name)

Marta
Ana
Gabi
Luz
Lorema


In [44]:
for player in team:
    print(player)

('Marta', 28, 'center')
('Ana', 22, 'point guard')
('Gabi', 22, 'shooting guard')
('Luz', 21, 'power forward')
('Lorema', 18, 'small forward')


In [45]:
for player in team:
    print(player[0])

Marta
Ana
Gabi
Luz
Lorema


### Compare lists, strings, and tuples

In [48]:
#Using triple quotes to write a string over multiple lines will insert newlines (\n).
my_string3="""
marathon
golfcart
"""

my_string3

'\nmarathon\ngolfcart\n'

In [49]:
my_string3 = """
marathon
golfcart
"""

my_string3

'\nmarathon\ngolfcart\n'

#### Strings
**content**
- Strings can contain any character-letters, numbers, punctutaion marks, spaces- but everthing between the opening and closing quotation marks is part of same single string.

**Mutability**
- Strings are immutable. This means that once a string is created, it cannot be modified. Any operation that appears to modify a string actually creats a new string object.

**Usage**
- Strings are most commonly used to represent text data.

**Methods**

- The python `string` class comes packed with many useful methods to mainpulat the data contained in strings. For more information on these methods refer to https://docs.python.org/3/library/string.html in the Python documentation. 


In [50]:
print(list('rocks'))
print(list(('stones','water','underground')))

['r', 'o', 'c', 'k', 's']
['stones', 'water', 'underground']


#### Lists
**Content**
- Lists can contain any data type, and in any combination. So, a single list can contain strings,integers, floats, tuples, dictionaries, and other lists.

**Mutability**
- Lists are **mutable**. This means that they can be modified after they are created.

**Usage**
- Lists are very versatile and therefore are used in numbers cases. Some common ones are:
    - Storing collections of related items
    - Storing collections of items that you want to iterate over: Because lists are ordered you can easily iterate over their elements using a for loop or list comprehension.
    - Sorting and searching: Lists can be sorted and searched, making them useful for tasks such as finding the minimum or maximum value in a list or sorting a list of items alphabetically.
    - Modifying existing data: Because lists are mutable, they are useful for situations in which you know you'll need to modify your data.
    - Storing results: Lists can be used to store the results of a computation or a series of operations, making them useful in many different programming tasks.

**Methods**
- You can find methods for the Python list class in  https://docs.python.org/3/tutorial/datastructures.html#more-on-lists in the Python documentation.

    

In [51]:
# Note: When using parentheses to declare a tuple with just a single element, you must use a trailing comma. 

test1=(1)
test2=(1,)

print(type(test1))
print(type(test2))


<class 'int'>
<class 'tuple'>


In [52]:
# No parentheses, but each element followed by a comma (even if there’s only one element):

tuple1=1,
tuple2=2,3,4,5

print(type(tuple1))
print(type(tuple2))

<class 'tuple'>
<class 'tuple'>


#### Tuples
**Content**
- Tuples can contain any data type, and in any combination. So, a single tuple can contain strings, integers, floats,lists, dictionaries, and other tuples.

**Mutability**
- Tuples are **immutable**. This means that once a tuple is created, it cannot be modified.

**Usage**
- Common uses of tuples include:
    - Returning multiple values from a function
    - Packing and unpacking sequences: You can use tuples to assign multiple values in a single line of code.
    - Dictionary keys: Because tuples are immutable, they can be used as dictionary keys,whereas lists cannot.
    Data integrity: Due to their immutable nature, tuples are a more secure way of storing data because they safeguard against accidental changes.

**Mehtods**
- Because tuples are built for data security, Python has only two methods that can be used on them:
    - `count()` returns the number of times a specified value occurs in the tuple.
    - `index()` searches the tuple for a specified value and returns the index of the first occurrence of the value.
    


Resources:
For more information about strings, refer to the
(https://docs.python.org/3/tutorial/introduction.html#strings)

For more information about lists, refer to the 
https://docs.python.org/3/tutorial/introduction.html#lists

For more information about tuples, refer to the 
https://docs.python.org/3/library/stdtypes.html#tuples

### More with loops, lists and tuples

In [53]:
team=[
     ('Marta',20,'center'),
     ('Ana',22,'point guard'),
     ('Gabi',22,'shooting guard'),
     ('Luz',22,'power forward'),
     ('Lorena',19,'small foreward')
]

In [58]:
def player_position(players):
    result=[]
    for name,age,position in players:
        result.append('Name{:>19} \nPosition:{:>15}\n'.format(name,position))
    
    return result

#{:>19} 表示字符串左侧的空格数

In [59]:
for player in player_position(team):
    print(player)

Name              Marta 
Position:         center

Name                Ana 
Position:    point guard

Name               Gabi 
Position: shooting guard

Name                Luz 
Position:  power forward

Name             Lorena 
Position: small foreward



In [63]:
for left in range(7):
    for right in range(left,7):
        print(f"[{left}|{right}]",end=" ")
    print('\n')

# range() 函数可创建一个整数列表，一般用在 for 循环中
# range(start, stop[, step]) 

[0|0] [0|1] [0|2] [0|3] [0|4] [0|5] [0|6] 

[1|1] [1|2] [1|3] [1|4] [1|5] [1|6] 

[2|2] [2|3] [2|4] [2|5] [2|6] 

[3|3] [3|4] [3|5] [3|6] 

[4|4] [4|5] [4|6] 

[5|5] [5|6] 

[6|6] 



In [66]:
dominoes =[]
for left in range(7):
    for right in range(left,7):
        dominoes.append((left,right))
dominoes

[(0, 0),
 (0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (0, 5),
 (0, 6),
 (1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (2, 2),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (4, 4),
 (4, 5),
 (4, 6),
 (5, 5),
 (5, 6),
 (6, 6)]

In [71]:
dominoes[7][0]
# 检查dominoes中第七个元素的第一个字符

(1, 1)

In [79]:
pips_from_loop=[]
print(dominoes)
for domino in dominoes:
    pips_from_loop.append(domino[0]+domino[1])
    print(domino[0],domino[1])
    print(pips_from_loop)

[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (3, 3), (3, 4), (3, 5), (3, 6), (4, 4), (4, 5), (4, 6), (5, 5), (5, 6), (6, 6)]
0 0
[0]
0 1
[0, 1]
0 2
[0, 1, 2]
0 3
[0, 1, 2, 3]
0 4
[0, 1, 2, 3, 4]
0 5
[0, 1, 2, 3, 4, 5]
0 6
[0, 1, 2, 3, 4, 5, 6]
1 1
[0, 1, 2, 3, 4, 5, 6, 2]
1 2
[0, 1, 2, 3, 4, 5, 6, 2, 3]
1 3
[0, 1, 2, 3, 4, 5, 6, 2, 3, 4]
1 4
[0, 1, 2, 3, 4, 5, 6, 2, 3, 4, 5]
1 5
[0, 1, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6]
1 6
[0, 1, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 7]
2 2
[0, 1, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 7, 4]
2 3
[0, 1, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 7, 4, 5]
2 4
[0, 1, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 7, 4, 5, 6]
2 5
[0, 1, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 7, 4, 5, 6, 7]
2 6
[0, 1, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 7, 4, 5, 6, 7, 8]
3 3
[0, 1, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 7, 4, 5, 6, 7, 8, 6]
3 4
[0, 1, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 7, 4, 5, 6, 7, 8, 6, 7]
3 5
[0, 1, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 7, 4

In [70]:
pips_from_loop=[]
for domino in dominoes:
    pips_from_loop.append(domino[0]+domino[1])
print(pips_from_loop)

[0, 1, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 7, 4, 5, 6, 7, 8, 6, 7, 8, 9, 8, 9, 10, 10, 11, 12]


#### List comprehension
Formulaic creation of a new list based on the values in an existing list


In [80]:
pips_from_list_camp=[domino[0]+domino[1] for domino in dominoes]

pips_from_list_camp ==pips_from_loop

True

### zip(),enumerate(), and list comprehension

#### zip()
The `zip()` function is built-in Python function that what the name implies: It performs an element-wise combination of sequence.

The function returns an **iterator** that produces tuples containing elements from each of the input sequences. An iterator is an object that enables processing of a collection of items one at a time without needing to assemble the entire collection at once. Use an iterator with loops or other iterable functions such as `list()` or `turple()`.

In [82]:
cities=['Paris','Lagos','Mumbai']
countries=['Frence','Nigeria','India','China']
places=zip(cities,countries)

print(places)
print(list(places))

[('Paris', 'Frence'), ('Lagos', 'Nigeria'), ('Mumbai', 'India')]


Notice that, in this case, the `list()` function is used to generate a list of tuples from iterator object. Here are a few things to keep in mind when using the`zip()` function.
- It works with two or more iterable objects. The given example zips two sequences, but the `zip()` function will accept more sequences and apply the same logic.
- If the input objects are of unequal length, the resulting iterator will be the same length as the shortest input.
- If you given it only one iterable object as an argument, the function will return an iterator that produces tuples containing only one element from that iterable at a time.

**Unzipping**

You can also unzip an object with the `*` operator 

In [83]:
scientists=[('Nikola','Tesla'),('Charles','Darwin'),('Marie','Curie')]
given_name,surnames=zip(*scientists)
print(given_name)
print(surnames)

('Nikola', 'Charles', 'Marie')
('Tesla', 'Darwin', 'Curie')


`enumerate()`

The `enmuerate()` function is another built-in Python function that allows you to iterate over a sequence while keeping track of each element's index. Similar `zip()`, it returns an iterator that produces pairs of indices and elements.

In [84]:
letters=['a','b','c']
for index,letter in enumerate(letters):
    print(index,letter)

0 a
1 b
2 c


In [85]:
letters=['a','b','c']
for index,letter in enumerate(letters,2):
    print(index,letter)

2 a
3 b
4 c


**List comprehension**

https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions

`my_list = [expression for element in iterable if condition]`

In this syntax:

- `expression` refers to an operation or what you want to do with each element in the iterable sequence.
- `element` is the variable name that you assign to represent each item in the iterable sequence.
- `iterable` is the iterable sequence.
- `condition` is any expression that evaluates to `True` or `False`. This element is optional and is used to filter elements of the iterable sequence.

In [86]:
numbers=[1,2,3,4,5]
new_list=[x+10 for x in numbers]
print(new_list)

[11, 12, 13, 14, 15]


In [87]:
words=['Emotan','Amina','Ibeno','Sankwala']
new_list=[(word[0],word[-1]) for word in words if len(word)>5]
print(new_list)

[('E', 'n'), ('S', 'a')]


## Dictionaries and sets

### Introduction to dictionaries

#### Dictionary
A data structure that consists of a collection of key-value pairs


In [90]:
zoo={
    'pen_1':'penguins',
    'pen_2':'zebras',
    'pen_3':'lines'
}

zoo['pen_2']

'zebras'

`dict()`

Function used to create a dictionary

In [92]:
zoo=dict(
    pen_1='monkeys',
    pen_2='zebras',
    pen_3='lions'
)
zoo['pen_2']

'zebras'

In [93]:
zoo['pen_4']='crocodiles'
zoo

{'pen_1': 'monkeys',
 'pen_2': 'zebras',
 'pen_3': 'lions',
 'pen_4': 'crocodiles'}

**Immutable keys**
- Integers
- Floats
- Tuples
- Strings

**Mutable data types cannot be used as keys**
- Lists
- Sets
- Other dictionaries




In [97]:
print('pen_1' in zoo)
print('pen_7' in zoo)

True
False


### Dictionary methods

In [104]:
team =[
    ('Marta',20,'center'),
    ('Ana',22,'point guard'),
    ('Gabi',22,'shooting guard'),
    ('Luz',21,'power forward'),
    ('Lorena',19,'small forward'),
    ('Sandra',19,'center'),
    ('Mari',10,'point guard')
]

In [107]:
new_team={
    'center':[('Marta',20),('Sandra',19)],
    'point guard':[('Ana',22),('Mari',10)],
    'shooting guard':[('Gabi',22),('Esme',18)],
    'power forward':[('Luz',21),('Lin',18)],
    'small forward':[('Lorena',19),('Sol',19)],

}

"new_team={\n    'center':[('Marta',20),('Sandra',19)],\n    'point guard':[('Ana',22),('Mari',10)],\n    'shooting guard':[('Gabi',22),('Esme',18)],\n    'power forward':[('Luz',21),('Lin',18)],\n    'small forward':[('Lorena',19),('Sol',19)],\n\n}"

In [115]:
new_team={}
for name, age, position in team:
    print(new_team)
    if position in new_team:
        new_team[position].append((name,age))
    else:
        new_team[position]=[(name,age)]

new_team[position]

{}
{'center': [('Marta', 20)]}
{'center': [('Marta', 20)], 'point guard': [('Ana', 22)]}
{'center': [('Marta', 20)], 'point guard': [('Ana', 22)], 'shooting guard': [('Gabi', 22)]}
{'center': [('Marta', 20)], 'point guard': [('Ana', 22)], 'shooting guard': [('Gabi', 22)], 'power forward': [('Luz', 21)]}
{'center': [('Marta', 20)], 'point guard': [('Ana', 22)], 'shooting guard': [('Gabi', 22)], 'power forward': [('Luz', 21)], 'small forward': [('Lorena', 19)]}
{'center': [('Marta', 20), ('Sandra', 19)], 'point guard': [('Ana', 22)], 'shooting guard': [('Gabi', 22)], 'power forward': [('Luz', 21)], 'small forward': [('Lorena', 19)]}


[('Ana', 22), ('Mari', 10)]

In [109]:
new_team[position]

[('Ana', 22), ('Mari', 10)]

In [116]:
new_team['point guard']

[('Ana', 22), ('Mari', 10)]

In [117]:
for x in new_team:
    print(x)

center
point guard
shooting guard
power forward
small forward


`keys()`

A dictionary method to retrieve only the dictionary's key

In [118]:
new_team.keys()

dict_keys(['center', 'point guard', 'shooting guard', 'power forward', 'small forward'])

`values()`

A dictionary method to retrieve only the dictionary's values

In [119]:
new_team.values()

dict_values([[('Marta', 20), ('Sandra', 19)], [('Ana', 22), ('Mari', 10)], [('Gabi', 22)], [('Luz', 21)], [('Lorena', 19)]])

`items()`

A dictionary method to retrieve both the dictionary's keys and values


In [120]:
new_team.items()

dict_items([('center', [('Marta', 20), ('Sandra', 19)]), ('point guard', [('Ana', 22), ('Mari', 10)]), ('shooting guard', [('Gabi', 22)]), ('power forward', [('Luz', 21)]), ('small forward', [('Lorena', 19)])])

In [121]:
for a, b in new_team.items():
    print(a,b)

center [('Marta', 20), ('Sandra', 19)]
point guard [('Ana', 22), ('Mari', 10)]
shooting guard [('Gabi', 22)]
power forward [('Luz', 21)]
small forward [('Lorena', 19)]


#### Creat a dictionary
There are two main ways to create dictionaries in Python
- Braces`{}`
- The dict function:`dict()`

In [122]:
smallest_countries = dict(africa='Seychelles',
                         asia='Maldives',
                         europe='Vatican City',
                         oceania='Nauru',
                         north_america='St. Kitts and Nevis',
                         south_america ='Suriname'
)

In [123]:
smallest_countries = {'Africa': 'Seychelles',
                     'Asia': 'Maldives',
                     'Europe': 'Vatican City',
                     'Oceania': 'Nauru',
                     'North America': 'St. Kitts and Nevis',
                     'South America': 'Suriname'
                     }

Some important notes about keys and values:

- **Dictionary keys**: Can be of any *immutable* data types, such as strings, numbers, or tuples

- **Dictionary values**: Can be of any data type- mutable or immutable- including other dictionaries or objects

- Each key can only correspond to a single value;

In [124]:
# Delete a key-value pair

my_dict={
    'num':[1,2,3],
    'abc':['a','b','c']
}

del my_dict['abc']
print(my_dict)

{'num': [1, 2, 3]}


#### Additional resources
- For more information about dictionaries, refer to the 
https://docs.python.org/3/tutorial/datastructures.html#dictionaries

- For more dictionary methods, refer to the
https://docs.python.org/3/library/stdtypes.html#mapping-types-dict

- For more information about view objects, refer to the
https://docs.python.org/3/library/stdtypes.html#dict-views

### Introduction to sets

#### Set
A data structure in Python that contains only unordered, non- interchangeable elements


Instantiated with `set()` function or non-empty braces.


`set()`

A function that takes an iterable as an argument and returns a new set objech

In [127]:
x = set(['foo','bar','baz','foo'])
print(x)

# each element must be unique in sets

{'foo', 'baz', 'bar'}


In [128]:
x = set('foo')
print(x)

{'o', 'f'}


In [129]:
x = set(('foo','bar','baz','foo'))
print(x)

{'foo', 'baz', 'bar'}


In [130]:
x={'foo'}
print(type(x))

y={}
print(type(y))

<class 'set'>
<class 'dict'>


To define an empty set, you have to use `set()`

`intersection()`

A function that finds the elements that two sets have in common

`union()`

A function that finds all the elements from both sets

`difference()`

A function that finds the elements present in one set, but not the other

`symmetric_difference()`

A function that finds elements from both sets that are mutually not present in the other

In [137]:
set1={1,2,3,4,5,6}
set2={4,5,6,7,8,9}

print(set1.intersection(set2))

print(set1 & set2)

print(set1.union(set2))

{4, 5, 6}
{4, 5, 6}
{1, 2, 3, 4, 5, 6, 7, 8, 9}


In [138]:
x1={'foo','bar','baz'}
x2={'baz','qux','quux'}

print(x1.union(x2))

print(x1|x2)

{'foo', 'bar', 'baz', 'qux', 'quux'}
{'foo', 'bar', 'baz', 'qux', 'quux'}


In [141]:
set1={1,2,3,4,5,6}
set2={4,5,6,7,8,9}

print(set1.difference(set2))

print(set1-set2)

{1, 2, 3}
{1, 2, 3}


In [143]:
print(set2.difference(set1))

print(set2-set1)

{8, 9, 7}
{8, 9, 7}


In [145]:
set1={1,2,3,4,5,6}
set2={4,5,6,7,8,9}

print(set2.symmetric_difference(set1))

print(set2^set1)

{1, 2, 3, 7, 8, 9}
{1, 2, 3, 7, 8, 9}


### Reference guide: Sets

#### Create a set
```
my_set={5,10,10,20}
```
There are two functions for creating sets inPython: `set()` and `frozenset()`. Use these on any iterable object. Or use these functions to creat empty sets.

`set()`

- This is a mutable data type.

- Because it's mutable, this class comes with
https://docs.python.org/3/library/stdtypes.html#frozenset.update

- It can be applied to any iterable object and will remove duplicate elements from it.

- It is unordered and non-indexable.

- Elements in a set must be hashable; Generally, this means they must be immutable.



In [147]:
example_a=[1,2,3,4,'a',2,2.0]

set(example_a)

{1, 2, 3, 4, 'a'}

In [148]:
example_b = ('apple', (1, 2, 2, 2, 3), 2)
set(example_b)

{(1, 2, 2, 2, 3), 2, 'apple'}

`frozenset()`

Frozensets are another type of set in Python. They are their own class, and they are similar to sets, except they are immutable.

- This is an immutable data type.

- It can be applied to any iterable object and will remove duplicate elements from it.

- Because they're immutable, frozensets can be used as dictionary key and as elements in other sets.


In [149]:
example_e=[1.5,frozenset(['a','b','c']),1.5]
set(example_e)

{1.5, frozenset({'a', 'b', 'c'})}

#### Set methods
Sets are useful to determine which values are contained in a data structure and to eliminate duplicate values. There are numberous set methods- such as intersection, union ,difference, and symmetric difference- that add functionality and power to working with sets.

In [151]:
# union()

set_1={'a','b','c'}
set_2={'b','c','d'}

print(set_1.union(set_2))
print(set_1|set_2)

{'b', 'a', 'c', 'd'}
{'b', 'a', 'c', 'd'}


In [154]:
# intersection()

set1={'a','b','v'}
set2={'b','c','d'}

print(set1.intersection(set2))
print(set1 & set2)

{'b'}
{'b'}


In [155]:
# difference()

set1={'a','b','c'}
set2={'c','d','e'}

print(set1.difference(set2))
print(set1-set2)

{'b', 'a'}
{'b', 'a'}


In [156]:
# symmetric difference()

set1={'a','b','c'}
set2={'c','d','e'}

print(set1.symmetric_difference(set2))
print(set1^set2)

{'b', 'a', 'd', 'e'}
{'b', 'a', 'd', 'e'}


In [44]:
def compareTriplets(a, b):
    i=0
    Alice=0
    Bob=0
    '''for i in range(0,len(a)):
        
        if a[i]<b[i]:
            Alice+=1
        elif a[i]<b[i]:
            Bob +=1
        elif a[i]==b[i]:
            break
        i+=1
    c=[Alice , Bob]
    return c
'''



In [45]:


compareTriplets([5,6,7], [3, 6, 10])

b



[3, 2, 1]

## Arrays and vectors with Numpy

### The power of packages

#### Libeary( or package)
Beoadly refers to a resuable collection of code

#### Python libraries
- **matplotlib**: A library for creating static, animated, and interactive visualizations in Python

- **Seaborn**: A visualization library based on matplotlib that provides a simpler interface for working with common plots and graphs

- **NumPy**: An essential library that contains multidimensional array and matrix data structures and functions to manipulate them

- **pandas**: A powerful library built on top of NumPy that's used to manipulate and analyze tabular data


#### Module 
A simple Python file containing a collection of functions and global variables

##### Commonly used Python modules
- Math

- Random

#### Global variables
Variables that can be accessed from anywhere in a program of script

### Introduction to NumPy

#### Vectorization
Enables operations to be performed on multiple components of data object at the same time


In [2]:
list_a=[1,2,3]
list_b=[2,4,6]



In [3]:
list_c=[]

for i in range(len(list_a)):
    list_c.append(list_a[i]*list_b[i])

list_c

[2, 8, 18]

In [4]:
import numpy as np

array_a=np.array(list_a)
array_b=np.array(list_b)

array_a*array_b

array([ 2,  8, 18])

#### Import statement
Uses the `import` keyword to load an external library, package, module, or function into your computing environment

#### Aliasing
Lets you assign an alternate name- or alias- by which you can refer to something


### Understand Python libraries, packages, and modules

#### Import statements


In [8]:
import numpy

numpy.array([2,4,6])



array([2, 4, 6])

#### Aliasing

In [10]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as plt

NumPy is used for high-performance vector and matrix computations. 

Pandas is a library for manipulating and analyzing tabular data.

Seaborn and matplotlib are both libraries used to create graphs, charts, and other data visualizations.

In [11]:
np.array([2,4,6])

array([2, 4, 6])

#### Additional import syntax

##### importing modules

In [12]:
import matplotlib.pyplot as plt

##### Importing functions

Just as you can import libraries and modules, you can also import individual functions from libraries or from modules within libraries using a specific syntax. 

**Here’s an example depicting a common import when using the scikit-learn library to build machine learning models:**

In [13]:
from sklearn.metrics import precision_score, recall_score


**Notice the different syntax**

- The import statement begins with the **from** keyword, followed by `sklearn.metrics`- the scikit-learn library + the `metrics` module.

- Next is the `import` keyword followed by the desired function. In this case, there are two: `precision_score` and 'recall_score`.

The same syntax can be applied to the example using NumPy's `array()` function.

In [14]:
from numpy import array

In [15]:
array([2,4,6])

array([2, 4, 6])

##### Discouraged syntax

If you wrote `from numpy import *`, you'd be able to use all of the NumPy's functions without proceding them with `numpy` or `np`.

**This approach is not recommended** because it makes it difficult to track where functions come from.

Howevre, it's helpful to be aware of this because you will likely encounter it in your work as a data professional. And, in specific instances, it might be useful.



In [ ]:
from library.module import *


#### Commonly used built-in moudles

such as ``math``, ``datatime``, and `random`

These can be imported without additional installation.

In other words, you can import them directly, as long as you have Python installed.


`datatime`

- Provides many helpful date and time conversions and calculations


In [20]:
import datetime

date=datetime.date(1977,5,8) #assign a date to a variable

print(date) # print date

print(date.year) # print the year that the date is in

delta = datetime.timedelta(days=30) #assign a timedelta of 30 days to a variable

print(date-delta)

1977-05-08
1977
1977-04-08


`math`

- Provide access to mathematical functions

In [21]:
import math

print(math.exp(0)) # e**0
print(math.log(1)) # ln(1)
print(math.factorial(4)) # 4!
print(math.sqrt(100)) #square root of 100

1.0
0.0
24
10.0


`random`

- Useful for generating random numbers

In [22]:
import random

print(random.random()) #0.0<=x<1.0

print(random.choice([1,2,3])) # choose a random element from a sequence
      
print(random.randint(1,10)) # a<=X<=b



0.2603913306276252
2
4


https://pypi.org/


### Basic array operations

#### N-dimensional array(ndarray)
The core data object of NumPy


n-dimensional array = ndarray

- The ndarray is a vector

- vectors enable many operations to be performed together when the code is executed, resulting in faster run-times that require less computer memory.

- ndarray are mutable, you can changes the values they contain.



In [23]:
import numpy as np

x=np.array([1,2,3,4])

x


array([1, 2, 3, 4])

In [24]:
x[-1]=5
x

array([1, 2, 3, 5])

In [26]:
arr=np.array([1,2,3,'change'])

print(arr)

print(type(arr[2]))

print(type(arr))

['1' '2' '3' 'change']
<class 'numpy.str_'>
<class 'numpy.ndarray'>


**dtype**

A NumPy attribute used to check the data type of the contents of an array

In [27]:
arr=np.array([1,2,34,])

arr.dtype

dtype('int64')

In [28]:
arr.shape

(3,)

**shape**

A NumPy attribute used to check the shape of an array

**ndim**

A NumPy attribute used to check the number of dimensions of an array

In [29]:
arr.ndim

1

In [32]:
arr_2d=np.array([[1,2],[3,4],[5,6],[7,8]])

print(arr_2d.shape)

print(arr_2d.ndim)

arr_2d

(4, 2)
2


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [35]:
arr_3d=np.array([[[1,2,3],[4,5,6]],[[5,6,7],[7,8,9]]])

print(arr_3d.shape)

print(arr_3d.ndim)


arr_3d

(2, 2, 3)
3


array([[[1, 2, 3],
        [4, 5, 6]],

       [[5, 6, 7],
        [7, 8, 9]]])

`reshape()`

NumPy method used to change the shape of an array

In [37]:
arr_2d=np.array([[1,2],[3,4],[5,6],[7,8]])

print(arr_2d.shape)

print(arr_2d.ndim)


(4, 2)
2


4 rows 2 columes **change to** 2 rows 4 columes

In [39]:
arr_2d=arr_2d.reshape(2,4)

arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
arr=np.array([1,2,3,4,5])

np.mean(arr)

3.0

In [41]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [42]:
np.floor(5.7)

5.0

In [44]:
np.ceil(5.3)

6.0

### Reference guide: Arrays

#### Create an array

`np.array`

This creat an `ndarray`(n-dimensional array). There is no limit to how many dimensions a NumPy array can have, but arrays with many dimensions can be more difficult to work.


In [45]:
arr_1d=np.array([1,2,3,4,5])

arr_1d

array([1, 2, 3, 4, 5])

In [48]:
arr_2d=np.array(
    [[1,2,3],[1,2,5]]
)

print(arr_2d.shape)

print(arr_2d.ndim)

print(arr_2d)

(2, 3)
2
[[1 2 3]
 [1 2 5]]


In [50]:
arr_3d=np.array([[[1,2],[4,5]
                  ],
                  [[2,2],[2,4]],
                  [[3,3],[3,5]]
                  ])

print(arr_3d.shape)

print(arr_3d.ndim)

print(arr_3d)

(3, 2, 2)
3
[[[1 2]
  [4 5]]

 [[2 2]
  [2 4]]

 [[3 3]
  [3 5]]]


`np.zeros()`

- This creates an array of a designed shape that is pre-filled with zeros:


In [52]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

`np.ones()`

- This creates an array of a designed shape that is pre-filled with ones:


In [53]:
np.ones((1,2))

array([[1., 1.]])

`np.fill()`

- And this creats an array of designed shape that is pre-filled with a specified value:

In [54]:
np.full((5,3),8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

These functions are useful for various situations:

- To initialize an array of a specific size and shape, then fill it with values derived from a calculation.

- To allocate memory fo laser use

- To perform matrix operations

#### Array methods



`ndarray.flatten()`

- This returns a copy of the array collapsed into one dimension

In [55]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print(
array_2d.flatten())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


`ndarray.reshape()`

- This given a new shape to an array without changing its data.

In [58]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()
print(array_2d.reshape(3, 2))
print(array_2d.ndim)

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]
2


Adding a value of -1 in the designed new shape makes the process more efficient, as it indicates for NumPy to automatically infer the value based on other given values.


In [59]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()
array_2d.reshape(3, -1)

[[1 2 3]
 [4 5 6]]



array([[1, 2],
       [3, 4],
       [5, 6]])

`ndarray.tolist()`

- This converts an array to a list object. Multidmensional arrays are convered to nested lists.


In [60]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()
array_2d.tolist()

[[1 2 3]
 [4 5 6]]



[[1, 2, 3], [4, 5, 6]]

#### Mathmatical functions
NumPy arrays also have many methods that are mathematical functions:

- `ndarray.max()`: returns the maximum value in the array or along a specified axis.

- `ndarray.mean()`: returns the mean of all the values in the array or along a specified axis.

- `ndarray.min()`: returns the minimum value in the array or along a specified axis.

- `ndarray.std()`: returns the standard deviation of all the values in the array of along a specified axis.



In [61]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print()

print(a.max())
print(a.mean())
print(a.min())
print(a.std())

[[1 2 3]
 [4 5 6]]

6
3.5
1
1.707825127659933


#### Array attributes

NumPy arrays have severl attributes that enable you to access information about the array. Some the most commonly used attributes include the following:


- `ndarray.shape`: returns a tuple of the array's dimensions

- `ndarray,dtype`: returns the data type of the array's contents

- `ndarray.size`: returns the total number of elements in the array.

- `ndarray.T`: returns the array transposed (rows become columns, columns become rows).

In [62]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()

print(array_2d.shape)
print(array_2d.dtype)
print(array_2d.size)
print(array_2d.T)

[[1 2 3]
 [4 5 6]]

(2, 3)
int64
6
[[1 4]
 [2 5]
 [3 6]]


#### Indexing and slicing

In [63]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print()

print(a[1])
print(a[0, 1])
print(a[1, 2])

[[1 2 3]
 [4 5 6]]

[4 5 6]
2
6


In [67]:
a = np.array([[(1, 2, 3), (4, 5, 6)],
             [(1, 2, 3), (4, 5, 6)]
             ])
print(a)
print()

print(a[1,0])
print(a[0, 1,2])


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]

[1 2 3]
6


In [68]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print()

a[:, 1:]

[[1 2 3]
 [4 5 6]]



array([[2, 3],
       [5, 6]])

#### Array operations

In [69]:
a = np.array([(1, 2, 3), (4, 5, 6)])
b = np.array([[1, 2, 3], [1, 2, 3]])
print('a:')
print(a)
print()
print('b:')
print(b)
print()
print('a + b:')
print(a + b)
print()
print('a * b:')
print(a * b)

a:
[[1 2 3]
 [4 5 6]]

b:
[[1 2 3]
 [1 2 3]]

a + b:
[[2 4 6]
 [5 7 9]]

a * b:
[[ 1  4  9]
 [ 4 10 18]]


#### Mutability

In [70]:
a = np.array([(1, 2), (3, 4)])
print(a)
print()

a[1][1] = 100
a

[[1 2]
 [3 4]]



array([[  1,   2],
       [  3, 100]])

In [71]:
a = np.array([1, 2, 3])
print(a)
print()

a[3] = 100
a

[1 2 3]



IndexError: index 3 is out of bounds for axis 0 with size 3